function Maindata1 = importfile(workbookFile, sheetName, dataLines)
%IMPORTFILE Import data from a spreadsheet
%  MAINDATA1 = IMPORTFILE(FILE) reads data from the first worksheet in
%  the Microsoft Excel spreadsheet file named FILE.  Returns the numeric
%  data.
%
%  MAINDATA1 = IMPORTFILE(FILE, SHEET) reads from the specified
%  worksheet.
%
%  MAINDATA1 = IMPORTFILE(FILE, SHEET, DATALINES) reads from the
%  specified worksheet for the specified row interval(s). Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  Maindata1 = importfile("C:\Users\Jirat Jalaketu\OneDrive\เดสก์ท็อป\My Study\Homework\second year\Prob Stat for EE\project\Main_data1.xlsx", "Sheet1", [79, 79]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 08-Dec-2021 20:18:38

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [79, 79];
end

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 5);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = "B" + dataLines(1, 1) + ":F" + dataLines(1, 2);

% Specify column names and types
opts.VariableNames = ["Q21", "Q32", "Q43", "Q12020Q4", "Q22021Q1"];
opts.VariableTypes = ["double", "double", "double", "double", "double"];

% Import the data
Maindata1 = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = "B" + dataLines(idx, 1) + ":F" + dataLines(idx, 2);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    Maindata1 = [Maindata1; tb]; %#ok<AGROW>
end

%% Convert to output type
Maindata1 = table2array(Maindata1);
end