function Maindata = importdpn(workbookFile, sheetName, dataLines)
%IMPORTFILE Import data from a spreadsheet
%  MAINDATA = IMPORTFILE(FILE) reads data from the first worksheet in
%  the Microsoft Excel spreadsheet file named FILE.  Returns the numeric
%  data.
%
%  MAINDATA = IMPORTFILE(FILE, SHEET) reads from the specified worksheet.
%
%  MAINDATA = IMPORTFILE(FILE, SHEET, DATALINES) reads from the
%  specified worksheet for the specified row interval(s). Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  Maindata = importfile("C:\Users\Jirat Jalaketu\OneDrive\เดสก์ท็อป\My Study\Homework\second year\Prob Stat for EE\project\Main_data.xlsx", "Sheet1", [3, 79]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 04-Nov-2021 17:48:59

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [3, 79];
end

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 5);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = "N" + dataLines(1, 1) + ":R" + dataLines(1, 2);

% Specify column names and types
opts.VariableNames = ["q2_2020_1", "q3_2020_1", "q4_2020_1", "q1_2021_1", "q2_2021_1"];
opts.VariableTypes = ["double", "double", "double", "double", "double"];

% Import the data
Maindata = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = "N" + dataLines(idx, 1) + ":R" + dataLines(idx, 2);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    Maindata = [Maindata; tb]; %#ok<AGROW>
end

%% Convert to output type
Maindata = table2array(Maindata);
end